spring.application.name=duplo

server.port=4353

# Database connection properties
#yeged15813@badgerhole.com
#yeged15813@badgerhole.com@
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://ep-mute-dawn-aqxayazo-pooler.c-8.us-east-1.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_tFPDUg3ym5Vv

# JPA properties
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.connection.CharSet=UTF-8
spring.jpa.properties.hibernate.connection.characterEncoding=UTF-8
spring.jpa.properties.hibernate.connection.useUnicode=true

upload.dir=uploads

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=200MB

it.step.app.jwtSecret=404E635266556A586E3272357538788652F413F4428472B4B6250645367566B5970