# Database connection settings
# livah75123@dwseal.com
# livah75123@dwseal.comQ
hibernate.connection.url=jdbc:postgresql://ep-withered-rain-al512eka-pooler.c-3.eu-central-1.aws.neon.tech/neondb?charSet=UTF8
hibernate.connection.username=neondb_owner
hibernate.connection.password=npg_Fa7uznIOeT2G

# Echo all executed SQL to console
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.highlight_sql=true

# Automatically export the schema
#hibernate.hbm2ddl.auto=create
hibernate.hbm2ddl.auto=update