server.port=8087

#cegiy92214@inreur.com
#cegiy92214@inreur.comQ
# Database connection properties
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://ep-late-dew-altxzm9p-pooler.c-3.eu-central-1.aws.neon.tech:5432/neondb
spring.datasource.url=jdbc:postgresql://localhost:5432/p32-fintech
#spring.datasource.url=jdbc:postgresql://localhost:5028/postgres
#spring.datasource.username=neondb_owner
spring.datasource.username=postgres
#spring.datasource.username=halosh
#spring.datasource.password=npg_whxVOHra38fK
spring.datasource.password=123456
#spring.datasource.password=mimi45Wh**xaxalala

# JPA properties
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.connection.CharSet=UTF-8
spring.jpa.properties.hibernate.connection.characterEncoding=UTF-8
spring.jpa.properties.hibernate.connection.useUnicode=true

#spring.jpa.properties.hibernate.jdbc.time_zone=Europe/Kiev