version: "3.9"

networks:
  javaNet:
    driver: bridge

services:
  postgresServerDb:
    image: postgres:18.1
    container_name: postgres_db
    restart: always
    ports:
      - "5020:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${VOLUME_POSTGRES}
    networks:
      - javaNet
    
  api:
    #build: ./WebApiTransfer
    image: novakvova/p32-java:latest
    container_name: p32-java_api
    volumes:
      - ${VOLUME_SERVERAPI}
      - ${VOLUME_MUSICAPI}
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresServerDb:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "5797:8087"
    depends_on:
      - postgresServerDb
    networks:
      - javaNet